### ISSUE TITLE
Django 3.x support

### ISSUE THREAD

**Issue by bducraux** [myyang/django-unixtimestampfield#3]
I am getting this error after update Django 2.2 to 3.0

```
 from unixtimestampfield.fields import UnixTimeStampField
  File "C:\Projects\.virtualenvs\project1-xsLDn82m\lib\site-packages\unixtimestampfield\__init__.py", line 1, in <module>
    from .fields import UnixTimeStampField
  File "C:\Projects\.virtualenvs\project1-xsLDn82m\lib\site-packages\unixtimestampfield\fields.py", line 65, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (C:\Projects\.virtualenvs\project1-xsLDn82m\lib\site-packages\django\utils\__init__.py)
```

Please evaluate the migration to [six](https://pypi.org/project/six/) as suggested in the [removed-private-python-2-compatibility-apis](https://docs.djangoproject.com/en/dev/releases/3.0/#removed-private-python-2-compatibility-apis) section of the release note.

Thanks for this amazing package!

**Comment by myyang** [comment]
We've fixed in PR #4.
